// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBok4H7m32gUhTkuqTLrUeRSKzP-Ue0P9Y',
    appId: '1:969179923560:web:a93895dcb10da3dd43a7dd',
    messagingSenderId: '969179923560',
    projectId: 'contacts-f95d2',
    authDomain: 'contacts-f95d2.firebaseapp.com',
    storageBucket: 'contacts-f95d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4OSCiJCD_Sfc1rBJu765jfVb-J2_feN8',
    appId: '1:969179923560:android:4f92c8b89a901f9a43a7dd',
    messagingSenderId: '969179923560',
    projectId: 'contacts-f95d2',
    storageBucket: 'contacts-f95d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKXDCaQIQkAaHE0tEjLgbsggrGpNu72Gs',
    appId: '1:969179923560:ios:92f44be2cecc192e43a7dd',
    messagingSenderId: '969179923560',
    projectId: 'contacts-f95d2',
    storageBucket: 'contacts-f95d2.firebasestorage.app',
    iosBundleId: 'com.example.googleContact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKXDCaQIQkAaHE0tEjLgbsggrGpNu72Gs',
    appId: '1:969179923560:ios:92f44be2cecc192e43a7dd',
    messagingSenderId: '969179923560',
    projectId: 'contacts-f95d2',
    storageBucket: 'contacts-f95d2.firebasestorage.app',
    iosBundleId: 'com.example.googleContact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBok4H7m32gUhTkuqTLrUeRSKzP-Ue0P9Y',
    appId: '1:969179923560:web:e681db1d34cd335e43a7dd',
    messagingSenderId: '969179923560',
    projectId: 'contacts-f95d2',
    authDomain: 'contacts-f95d2.firebaseapp.com',
    storageBucket: 'contacts-f95d2.firebasestorage.app',
  );
}
